name: DeathSwap
version: 1.3
main: com.boes.deathswap.DeathSwap
api-version: 1.21
commands:
  deathswap:
    description: Control the DeathSwap game.
    usage: /deathswap <start|stop|reload|spectate|leave>
    permission: deathswap.use
permissions:
  deathswap.use:
    description: Allows use of /deathswap commands
    default: true
  deathswap.admin:
    description: Allows admin-only commands (start, stop, reload)
    default: op
